AWSTemplateFormatVersion: "2010-09-09"

Resources:
  DynamoDBSessionInfoTableV1:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.sessionInfoDBTableV1Name}
